### ISSUE TITLE
Pedigree from Relatedness

### ISSUE THREAD

**Issue by ThatLionLady** [RHagenson/relped#1]
# Input

The input would be a sq or tri matrix of pairwise comparisons of relatedness and a table of demographic information for each individual including sex, age, and known parentage.

# Output

A pedigree tree of most likely relations. Unrelated individuals would be stand-alone while related individuals will be connected via a family tree network. An SVG would be ideal so the graphic can be manipulated if needed.

# Rejection/Termination Conditions

It might be a good idea to include age data somehow to help with generation assignment. That way Parent and Offspring can't accidentally be swapped if there aren't any other relationships to help determine direction.

# Similar tools

[Are there similar such tools in existence? How is this tool different?]

# Description

This tool would draw a family tree pedigree based on the degree of genetic relatedness (R). Expected R-values for consanguinity -- first (0.5), second (0.25), thirds (0.125), fourth (0.0625), etc. -- can be used as thresholds to guide assignment. 
![Table_of_Consanguinity](https://user-images.githubusercontent.com/44615083/67304033-e1257900-f4b8-11e9-9d0e-3c8523d7bec7.gif)

* Table source is [Wikipedia](https://en.wikipedia.org/wiki/Consanguinity)

Most pedigree drawing programs require a list of sires and dams. This would be a tool for when you have the genetic data but do not have definitive parent/offspring information and want a pedigree for determining possible relationship clusters. 

# Research Purpose

This tool will be for visualizing relationships in a sample population to assess relatedness and the possibility of inbreeding.

**Comment by rhagenson** [comment]
Decision was made to round the result of:

> ![8d984b610d248a5ebcdd7bf6aafd3e41](https://user-images.githubusercontent.com/5414719/67414072-fa492b00-f587-11e9-982a-ce6f9303dc54.png)

as either floor or ceiling would systematically over or underestimate relational distance.

**Comment by rhagenson** [comment]
Decision to use [gonum/graph](https://godoc.org/gonum.org/v1/gonum/graph) -- even though I do not prefer its API, I prefer its active development.

**Comment by rhagenson** [comment]
Decisions to pseudo-roll my own Graphviz writer via use of [gographviz](https://github.com/awalterschulze/gographviz). The builtin support for Graphviz/DOT in gonum/graph does not suit the needs of the application (no ability to write the names of nodes, only IDs).

**Comment by rhagenson** [comment]
Note: The whole "known indvs are IDed > 0, unknowns are IDed < 0" idea was scraped when that would have made it require two paths: one for adding knowns and another for adding unknowns. One addition path with a map from name to ID was deemed cleaner.

**Comment by rhagenson** [comment]
@ThatLionLady, the tool is now in the originally described form. It runs a bit slowly, but that is not terribly surprising for the first pass. What I can likely do to speed it up is to move away from using [gonum/graph](https://godoc.org/gonum.org/v1/gonum/graph) directly to implementing its interfaces myself.

![ml-sample-out txt](https://user-images.githubusercontent.com/5414719/67897034-94324a00-fb2b-11e9-8430-041581ee4bff.png)

A small sample of what the output currently looks like. Both three-column and ML-Relate inputs are implemented. My plans are still to clean up the implementation a bit (refactor!) and that should make it run a bit smoother

**Comment by rhagenson** [comment]
Closing this issue as the original plan has been implemented. Any additions/corrections should exist as new issues.

**Comment by rhagenson** [comment]
Better table of consanguinity:

![Table of Consanguinity - Full v2](https://user-images.githubusercontent.com/5414719/69372948-54f9a380-0c68-11ea-8c7b-18dadb66e640.jpg)
