### ISSUE TITLE
Limit number of entries?

### ISSUE THREAD

**Issue by rhagenson** [RHagenson/relped#12]
After attempting to run Graphviz on the `relped` output of ~ 10k entries and it taking ~ 6 hours to generate the image only for the image to be invalid/useless, I suspect some sort of realistic limit should placed on how many entries are allowed by `relped` to avoid a user from wasting their time running it only for the downstream to fail like it did for me. 

As I am never in support of hardcoded semi-arbitrary limits, I would also require the addition of a `--force/--f` option that ignores such limits. (If a user wants to generate the pedigree file for whatever reason they should be able to as long as I know the resulting file does not contain known errors.)

**Comment by RHagenson** [comment]
Female nodes should be circular, male nodes should be square, and unknowns are diamonds.

**Comment by rhagenson** [comment]
Decisions to limit number of nodes in final pedigree to 500 and back-propagate the math to limit the number of knowns individuals that one can process assuming all knows will be separated by exactly `--max-distance` number of unknowns.

**Comment by rhagenson** [comment]
Given:

```
T = k + n

k = d * n * (n - 1) * 1/2
```

where k is number of unknowns, n is number of knowns, and T is the total number of nodes, solving for n is:

![456dxu](https://user-images.githubusercontent.com/5414719/68884984-ee114300-06d9-11ea-8201-e2bcc87e7d29.png)

T would be a constant at compile time, but there is no way to know d before runtime.

**Comment by rhagenson** [comment]
@ThatLionLady now that I review this, I think limiting the pedigree to 500 is way too high of a threshold for most cases. When solving the above formula with T = 500 and d = 9, n = 10.9 => floor(10.9) = 10, as well with T = 500 and d = 3, n = 18.4 => floor (18.4) = 18

The T = 500 number will be a constant in use within the program, but can be changed at a latter time.

**Comment by rhagenson** [comment]
The math I did above is wrong as it over estimates the number of unknowns. Solving k when n = 50 and d = 1 (only map parent-offspring) leads to k = 1225, which is of course wildly wrong as mapping only parent-offspring means k = 0.

**Comment by rhagenson** [comment]
As the number of final nodes is dependent on the values themselves, not the number of values, I have decided I will not fix/enhance `relped` in this way (at least yet).
