### ISSUE TITLE
Limit ML-Relate Format to 3-columns

### ISSUE THREAD

**Issue by ThatLionLady** [RHagenson/relped#18]
Have input be a 3-column format with ID1, ID2, Relationship (PO, FS, HS, U) OR Relatedness (int). This can use ML-Relate output as well as relatedness output from other sources and simplify by having only one input.

**Comment by rhagenson** [comment]
To further what @ThatLionLady said above, the new singular input format would be:

ID1 | ID2 | Rel 
-----|------|------
<uint;string> | <uint;string> | <float;PO:FS:HS:U>

Therefore any definite known relationships can be denoted using their code directly, where as unknowns in need of inference can be denoted with relatedness score.

Example:

ID1 | ID2 | Rel
-----|------|--------
527 | 529 | -0.477
528 | 527 | U
528 | 529 | 0.131
528 | 531 | -0.281
540 | 528 | PO
