### ISSUE TITLE
Called HS should have only one step between individuals

### ISSUE THREAD

**Issue by ThatLionLady** [RHagenson/relped#32]
When HS are called, there should be only one step between two individuals. It currently assigns two unknown connections between HS with unknown parents.

HS two individuals share one parent so there should be one step shared in one direction, then the other direction will not be shared.

**Comment by rhagenson** [comment]
To clarify for myself when I get around to fixing this:

Input:

```csv
mother,child1,PO
mother,child2,PO
child1,child2,HS
```

Should yield

```dot
mother--child1
mother--child2
```

Not as it is building currently of:

```dot
mother--child1
mother--child2
child1--unknown1
unknown2--unknown2
unknown2--child2
```

A called HS could either have one parent of **one** unknown between them, not connections to a parent and/or two unknowns between them.
