### ISSUE TITLE
Review: Add Brief on Relatedness

### ISSUE THREAD

**Issue by rhagenson** [RHagenson/relped#40]
The question arose during review (https://github.com/openjournals/joss-reviews/issues/2124) that relatedness, its measure and purpose, are not discussed in either the manuscript, nor the documentation. A brief must be added in both places:

- [x] Manuscript: add paragraph on relatedness, its measure and purpose
- [x] Documentation: add paragraph on relatedness, its measure and purpose

**Comment by rhagenson** [comment]
@ThatLionLady, I will fix this on a separate Git branch so you can approve of the changes prior to them becoming official. Have not made the branch yet, but when I do I will direct you to it in this thread. Sound fair to you?

**Comment by ThatLionLady** [comment]
Sounds good.

>

**Comment by rhagenson** [comment]
Addition to manuscript in 85571af32369276a1e5fcd8bcdb518db6aa595ac
Addition to documentation in 0ff3d7a93873aab00a11c4b3e498add57421a2ee

@ThatLionLady, you should have Pull Request (PR) assigned to you now. If you go to https://github.com/rhagenson/relped/pull/41/files you will see the side-by-side of the two versions. If you approve of the changes, you should be able to mark them as approved. Otherwise, make any comments in the PR thread and I will make edits accordingly until you approve then we will merge the changes.
